### ISSUE TITLE
The store type 'nchar' could not be found in the Effort provider manifest

### ISSUE THREAD

**Issue by crathmann** [zzzprojects/EntityFramework-Effort#111]
Hi,

We have a property mapping like this: 

`Property(x => x.Test).HasColumnName(@"Test").HasColumnType("nchar").IsRequired().IsFixedLength()`

Unfortunately, Effort doesn't work with this Mapping. We get the following error message: 

> The store type 'nchar' could not be found in the Effort provider manifest

If we remove the mapping, Effort works like expected. The issue seems to be related to #104.

**Comment by JonathanMagnan** [comment]
Hello @crathmann ,

Thank you for reporting,

Yes, it looks the nvarchar mapping is here but not the nchar.

We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @crathmann 

The v1.3.4 has been released with the `nchar` support.

Let me know if that's working.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @crathmann ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
