### ISSUE TITLE
Ambiguous Match Issue (System.Reflection.AmbiguousMatchException)

### ISSUE THREAD

**Issue by MarkPigram** [zzzprojects/EntityFramework-Effort#134]
Hi, 

Thanks for a good tool, which we've been using for a while to assist with testing. 

I've run into an issue that I'm pretty stuck on and looking for some guidance on how it might be identified and resolved. 

Firstly the issue is limited to the unit testing via Effort. It doesn't occur with with a 'normal' DB connection (to an SQL Server). 

We've got a class hierarchy which includes:
-  ClassA -> ClassB -> ClassC 
-  ClassA -> ClassB -> ClassD. 

Within this 

- the primary key (CommonId) is set in ClassA
- a 'Name' property  set in ClassB. 
- Other properties in ClassC / ClassD, which aren't relevant to this (I think). 
- ClassD has a FK to ClassC, again I don't think this is relevant but I may be wrong

After populating the database the following behaviours occur

- Loading a ClassC (via repository.Get(x => x.CommonId == 123)) works fine
- Loading a ClassC (via repository.Get(x => x.Name == 'ABC')) works fine
- Loading a ClassD (via repository.Get(x => x.CommonId == 123)) works fine
- Loading a ClassD (via repository.Get(x => x.Name == 'ABC')) throws an Ambiguous Match exception
- Loading just the name (or other property) (via repository.Get(x => x.Name == 'ABC').Select(d => d.Name)) works fine.

I've been up and down the code and can't find a duplication of 'Name' or anything else which is the usual cause of an Ambiguous Match exception. Given that using the 'normal' DB works without issue, my current working theory is that the creation of the DB in Effort is where the duplication is occurring. 

Do you have any thoughts on why this might be, what I can do to further track down the root cause, or what further information you might need to assist. 

Thanks,
Mark

**Comment by JonathanMagnan** [comment]
Hello @MarkPigram ,

Thank you for reporting, I have added this request to our todo list.

My developer should be able to start to look at it on Friday or at the beginning of next week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @MarkPigram ,

My developer tried several scenarios to reproduce this issue but unfortunately, he was not able to find how to get this error.

It's possible to provide a basic project sample with the current issue?

Best Regards,

Jonathan

**Comment by MarkPigram** [comment]
Hi @JonathanMagnan,

Thanks for the update. I've been working towards a basic project to confirm what I'd experienced in our full application and allow you and your team to see the issue. Unfortunately, I've been pulled in a couple of other directions over the last week or so and haven't got one I can point you at. As soon as I do, I'll update you. 

Cheers,
Mark

**Comment by JonathanMagnan** [comment]
Hello @MarkPigram ,

This issue will be closed since we haven't heard back from you.

But it will get re-opened as soon as you will be able to provide more information.

Best Regards,

Jonathan
