### ISSUE TITLE
EffortProviderServices doesn't inherit from 'System.Data.Entity.Core.Common.DbProviderServices'

### ISSUE THREAD

**Issue by aureole82** [zzzprojects/EntityFramework-Effort#14]
I get a `System.InvalidOperationException` on the second line:

``` c#
    var connection = DbConnectionFactory.CreatePersistent(Guid.NewGuid().ToString());
    ApplicationDbContext db = new ApplicationDbContext(connection);
```

It happens inside the `Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext<ApplicationUser>.ctor` I'm deriving from:

``` c#
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbConnection connection) : base(connection, false)
        {
        }
    }
```

Here's the complete exception

```
System.InvalidOperationException occurred
  HResult=-2146233079
  Message=The 'Instance' member of the Entity Framework provider type 'Effort.Provider.EffortProviderServices, Effort, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6a46696d54971e6d' did not return an object that inherits from 'System.Data.Entity.Core.Common.DbProviderServices'. Entity Framework providers must inherit from this class and the 'Instance' member must return the singleton instance of the provider. This may be because the provider does not support Entity Framework 6 or later; see http://go.microsoft.com/fwlink/?LinkId=260882 for more information.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Infrastructure.DependencyResolution.ProviderServicesFactory.GetInstance(Type providerType)
       at System.Data.Entity.Internal.AppConfig.<.ctor>b__2(ProviderElement e)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Data.Entity.Infrastructure.DependencyResolution.AppConfigDependencyResolver.RegisterDbProviderServices()
       at System.Data.Entity.Infrastructure.DependencyResolution.AppConfigDependencyResolver.GetServiceFactory(Type type, String name)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at System.Data.Entity.Infrastructure.DependencyResolution.AppConfigDependencyResolver.GetService(Type type, Object key)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key)
       at System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService[T](IDbDependencyResolver resolver)
       at System.Data.Entity.DbContext.InitializeLazyInternalContext(IInternalConnection internalConnection, DbCompiledModel model)
       at Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext`1..ctor(DbConnection existingConnection, Boolean contextOwnsConnection)
       at MyProject.ApplicationDbContext..ctor(DbConnection connection) in ..\MyProject\ApplicationDbContext.cs:Zeile 16.
  InnerException: 
```

I tried to fix the `App.config` but it didn't help

``` xml
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <configSections>
        <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
      </configSections>
      <entityFramework>
        <providers>
          <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        </providers>
      </entityFramework>
    </configuration>
```

**Comment by kpko** [comment]
I have the same problem since I updated my effort package. This breaks all my tests unfortunately.

**Comment by tamasflamich** [comment]
Hi,

Which version of Entity Framework and Effort are you using?

**Comment by aureole82** [comment]
Here's my `packages.config`:
```xml
<packages>
  <package id="Effort.EF6" version="1.0.0" targetFramework="net452" userInstalled="true" />
  <package id="Effort.Extra.EF6" version="1.2.3" targetFramework="net452" userInstalled="true" />
  <package id="EntityFramework" version="6.1.2" targetFramework="net452" userInstalled="true" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.0" targetFramework="net452" userInstalled="true" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.0" targetFramework="net452" userInstalled="true" />
  <package id="NMemory" version="1.0.0" targetFramework="net452" userInstalled="true" />
  <package id="NUnit" version="2.6.4" targetFramework="net452" userInstalled="true" />
</packages>
```

**Comment by baumann74** [comment]
I am facing the same issue. Any solution to the problem?

**Comment by rpinto** [comment]
Same problem here

**Comment by kfrancis** [comment]
This is still an issue. The issue is that they have the same DLL filename.

**Comment by robert-j-engdahl** [comment]
> This is still an issue. The issue is that they have the same DLL filename.

Uh, but then it should be easy enough to fix.  Just up a major version number and change the name of the DLL; if thats what it takes to fix a bug that is as critical as this, that is the way to go IMHO.

**Comment by redplane** [comment]
Any solutions ?

I'm having the same issue.

**Comment by JonathanMagnan** [comment]
Hello @redplane ,

The suggestion from @robert-j-engdahl to rename look good but might cause also some side effect.

We will make a choice this week about if we want to go with this solution.

Best Regards,

Jonathan

**Comment by robert-j-engdahl** [comment]
I don't know if my suggestion will actually work.

The rename can be made in a non-problematic way by just copying the
provider to a new namespace in a new assembly.  That way, whatever worked
before continues to work.

I tried the above.  However, there is nothing anyone can do about this in
my setup, as I use NCrunch to run my tests, and .DLL's only seem copied
when first accessed, so dynamically loading anything from a named .DLL will
not work (not before NCrunch handles these App.config mentioned .DLLs).

Den man. 1. okt. 2018 kl. 22.51 skrev Jonathan Magnan <
notifications@github.com>:

**Comment by KozhevnikovDmitry** [comment]
Possible cause of the issue is considered in [question on STO](https://stackoverflow.com/questions/52571100/effort-autofac-did-not-return-an-object-that-inherits-from-dbproviderservice). It could be confusion between Effort and Effort.EF6.

**Comment by JonathanMagnan** [comment]
Hello all,

Just to let you know that we are currently preparing a release for this fix.

Finally after thinking about it, simply using a different key to strongly name the assembly may be the best solution.

No need to rename the assembly, namespace or whatever since they will now be considered as a different assembly which they are anyway!

The `Effort.EF6` will keep the same signing key while the `Effort` will now use a new key.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello all,

The v2.0.0 has been released.

Make sure to read the release note as some third party libraries may require assembly binding: https://github.com/zzzprojects/EntityFramework-Effort/releases/tag/v2.0.0

Let me know if that issue is now solved.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @robert-j-engdahl ,

You will find the project here: https://github.com/zzzprojects/EntityFramework-Effort/tree/master/Main/Source/lab/Z.Lab.NamingIssue

As you will see
- The project work with v2.x (even if `Effort` 1.x and 2.x is inside the project)
- The project doesn't work with v1.x

Let me know if you need more information.

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been resolved to start from v2.x (A stable version should be very soon available)

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
