### ISSUE TITLE
nuget package fails

### ISSUE THREAD

**Issue by b5white** [zzzprojects/EntityFramework-Effort#146]
I have all the tests passing. Now just need to undo everything I did to debug the issue and check it in.

I installed the Effort project from github into my project in order to trace into the code and resolve an issue. Now that I have it working, I've removed the source project and gone back to the nuget package. Now I get:    

"Message: Initialization method DataAccessTests.Accessors.ClientAccessorTests.Initialize threw exception. System.TypeInitializationException: System.TypeInitializationException: The type initializer for 'Effort.Internal.DbManagement.Engine.Services.ExtendedKeyInfoFactory' threw an exception. ---> System.TypeLoadException: Method 'CreateTable' in type 'Effort.Internal.DbManagement.Engine.ExtendedTableService' from assembly 'Effort, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6a46696d54971e6d' does not have an implementation.."

NMemory is fine, just chokes on Effort.

I suspected that it was compiling against one DLL and running against another.
I've verified that it is not pulling another version from the GAC. It is copying into the Debug folder. 
Procmon verifies that is reading from the bin\debug copy.

The nuget dll is v 1.3.10.0.
Compiled from source is 2.0.0.0.
NMemory is 2.0.7.0.

The nuget dll path is packages\Effort.EF6.1.3.10\lib\net45
Compiled from source path is EntityFramework-Effort-master\Main\Source\Effort.EF6.Net45\bin\Debug

Cleaned and rebuilt the project.
Deleted the Debug folder.
Removed the nuget package and reinstalled it. 
Restarted VS. 
Rebooted machine.

This was working before I installed the source version. Source control doesn't show any related changes in config files.

I can't believe that 'CreateTable' is a new method in 2.0.
What else could it be?

**Comment by Danghor** [comment]
The issue seems to be NMemory though. It works using Effort.EF6 v1.3.10 and NMemory v.2.0.4 and it crashes using Effort.EF6 v1.3.10 and NMemory v.2.0.5.

**Comment by b5white** [comment]
That fixed it. Thanks!

**Comment by JonathanMagnan** [comment]
Hello @b5white , @Danghor ,

Just to let you know,

We will try tomorrow to make a stable release for Effort.EF6 2.x, so people will no longer get this error that already been fixed in v2.x packages.
