### ISSUE TITLE
Sequence contains no matching element. Nvarchar2 type issue

### ISSUE THREAD

**Issue by azaharov** [zzzprojects/EntityFramework-Effort#149]
You had a problem with nvarchar type (https://github.com/zzzprojects/EntityFramework-Effort/issues/10).
I faced with same error, but with type nvarchar2) Have you plans to fix it?

**Comment by JonathanMagnan** [comment]
Hello @azaharov ,

Which provider are you using?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by azaharov** [comment]
> Hello @azaharov ,
> 
> Which provider are you using?
> 
> Best Regards,
> 
> Jonathan

Hello, @JonathanMagnan
I'm using EF for Oracle https://www.nuget.org/packages/Oracle.ManagedDataAccess.EntityFramework/.

**Comment by JonathanMagnan** [comment]
Thank you,

My developer normally assigned to `Effort` would be back from vacancy this Thursday, I will give this info to him.

**Comment by JonathanMagnan** [comment]
Hello @azaharov ,

The v2.0.2 has been released, the type `nvarchar2` has been added.

If more type is missing, please provide us your `EDMX` file: https://entityframework-extensions.net/edmx

Best Regards,

Jonathan

**Comment by azaharov** [comment]
Hello @JonathanMagnan ,
Sorry, I can't provide `EDMX` to you cause of NDA. But now I have an issue with varchar2(
I remember that I had no varchar2 problem in previous version.

**Comment by JonathanMagnan** [comment]
Hello @azaharov ,

That's why the `EDMX` is required. `Effort` was not supporting multiple `Oracles` columns before, so unless you provide it, we will need to fix it type per type which is not really efficient.

You can either send it in private here: `EDMX` or provide a distinct list of all your types and we will check what we can do.

**Comment by azaharov** [comment]
@JonathanMagnan 
We have only this two specified types: `nvarchar2 `and `varchar2`.

**Comment by JonathanMagnan** [comment]
Hello @azaharov ,

The v2.0.3 has been released.

Let me know if your model now works correctly.

Best Regards,

Jonathan

**Comment by azaharov** [comment]
Hello, @JonathanMagnan 
Now it works. Thank you!
