### ISSUE TITLE
Cloning an expensively initialized DB?

### ISSUE THREAD

**Issue by adams85** [zzzprojects/EntityFramework-Effort#150]
Hi!

I'm trying to find a viable method to unit test a legacy ASP.NET app which uses EF6 Model First and Effort looks like exactly what I'm looking for.

However, I've got a problem: the DB needs to be initialized with a bunch of master data. There's a complicated legacy code that takes an EF context and performs this initialization. It works fine with Effort contexts, too: the DB gets populated as expected. However, the initialization process is extremely slow (20-30 secs). Obviously, this makes creating a new DB context from scratch per test case unacceptable.

Is there a way to workaround this in Effort? The first idea that come to my mind is that I should create a fully initialized, "master" DB instance, then copy or clone this somehow per test case. Is there a way to do this in Effort? Using data loaders maybe?

The other option could be object pooling + creating/restoring snapshots. I found out there's some support for snapshots in Effort: EffortConnection.CreateRestorePoint/RollbackToRestorePoint. I made some experiments with this but with no luck, unfortunately. RollbackToRestorePoint doesn't seem to work for my model: throws exception complaining about foreign key violations...

**Comment by JonathanMagnan** [comment]
Hello @adams85 ,

Do you think you could provide a standalone project that throws the foreign key violations?

Looking at your requirement, I believe `Effort` can do it but the key is to make the `RollbackToRestorePoint` works

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by adams85** [comment]
Hi Jonathan!

Unfortunately, I cannot share any part of the code as it's confidential and it'd be very hard to create something identical.

However, thanks for the fast reply and for pointing me into the right direction! I'll try to make it work using RollbackToRestorePoint.

Cheers,
Adam
