### ISSUE TITLE
Transaction timeout fixed to 15 seconds

### ISSUE THREAD

**Issue by D101M** [zzzprojects/EntityFramework-Effort#156]
Hello,

our (sometimes heavy loaded) build-server runs into a TransactionAbortedException (as the transaction times out after 15 seconds). We did not figure out any way to increase that value (which is the default value of the DbConnection class and has no setter). In our integration tests we simulate some heavy data operations with some 100k changes per transaction. On our dev-machines it works awesome and the timeout exception is thrown very rarely. Especially when the build-server is heavy loaded the exception mentioned above will be thrown regularly. ... and no, more/better hardware is not really an option :-)

It's possible to make this value configurable or even better to use the DbContext.Database.CommandTimeout property instead, as, in my opinion, the connection timeout is the wrong property to use for commands while there exists a dedicated command timeout property.

While in V 1.x the ICommandAction interface had a timeout parameter (which held the value of the  Database.CommandTimeout) which could be used, that property has been removed in newer versions.

As a workaround, we implemented a SetConnectionTimeout method on the EffortConnection to set the timeout after initializing the connection.

**Comment by JonathanMagnan** [comment]
Hello @D101M ,

The v2.0.5 has been released.

We also implemented the method `SetConnectionTimeout` on the `EffortConnection` as you suggested.

Let me know if everything now works as expected.

```csharp
var connection = Effort.DbConnectionFactory.CreateTransient();

// SEED
using (var context = new EntityContext(connection))
{
    connection.SetConnectionTimeout(500000); 
}
```

Best Regards,

Jonathan

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by D101M** [comment]
Hello Jonathan,

thanks for the fast reply. We switched to the v2.0.5 and everything works as expected.

Best regards
