### ISSUE TITLE
String.Equals ignore case doesn't work (StringComparison.InvariantCultureIgnoreCase)

### ISSUE THREAD

**Issue by jons-aura** [zzzprojects/EntityFramework-Effort#161]
I found this pull request https://github.com/zzzprojects/EntityFramework-Effort/pull/58 but it doesn't appear to be in the current release (2.0.5)

I have a block of code that does
`queryable = queryable.Where(o => lastname.Equals(o.LastName, StringComparison.InvariantCultureIgnoreCase));`
and expect it to return 3 results of varying case but it only returns the one result that is an exact match.

**Comment by JonathanMagnan** [comment]
Thank a lot ;)

I will try to have my developer to look at it tomorrow.

**Comment by JonathanMagnan** [comment]
Hello @jons-aura ,

My developer told miss you missed the line 

```csharp
((EffortConnection)connection.StoreConnection).IsCaseSensitive = false;
```

To handle your table as case insensitive. I don't think it's currently possible to do it query by query at this moment.

Let me know if that solution can work for you.

Best Regards,

Jonathan

**Comment by jons-aura** [comment]
That works, the pull request I mentioned above has DbConnectionFactory in its example while I'm using EntityConnectionFactory and I didn't realize I'd have to cast it. Thanks!

**Comment by JonathanMagnan** [comment]
I believe you need to create the database first:

```csharp
var connection = Effort.DbConnectionFactory.CreateTransient();

using (var context = new EntityContext(connection))
{
	context.Database.CreateIfNotExists();
}

connection.IsCaseSensitive = false;
```

or simply do any other operation before the `IsCaseSentitive` such as:

```csharp
var connection = Effort.DbConnectionFactory.CreateTransient();

using (var context = new EntityContext(connection))
{
	context.EntitySimples.RemoveRange(context.EntitySimples);
	context.SaveChanges();
}

connection.IsCaseSensitive = false;
```
