### ISSUE TITLE
CsvTool doesn't include schema name in output filename

### ISSUE THREAD

**Issue by martindafonte** [zzzprojects/EntityFramework-Effort#166]
### Description
When I export my database to csv, the files that are created don't include the schema in the filename. If there are multiple tables with the same names in different schemas, only the last table's file remain after the export.

### Further technical details
- EF version: 6
- EF Effort version: 
- Database Provider: SQL 

### Possible solution

In the file 
Effort.CsvTool\ViewModels\MainViewModel.cs line 215
change from:
` FileInfo file = new FileInfo(Path.Combine(dir.FullName, string.Format("{0}.csv", name)));`
to
` FileInfo file = new FileInfo(Path.Combine(dir.FullName, string.Format("{0}.{1}.csv", schemaName, name)));`

The CsvDataLoader already expects the schema name separeted with a dot

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

Your pull has been merged.

Best Regards,

Jonathan
