### ISSUE TITLE
StartsWith is not respecting IsCaseSensitive

### ISSUE THREAD

**Issue by Agendum** [zzzprojects/EntityFramework-Effort#174]
### Description
Turning off IsCaseSensitive does allow string equality checks to be case-insensitive. However, StartsWith is not honoring the flag.

### Exception
N/A

### Project
Below is full running project which reproduces and demonstrates the bug. The code follows the same pattern presented by [https://github.com/zzzprojects/EntityFramework-Effort/blob/master/Main/Source/test/Effort.Test.EF6/Features/StringFieldFixture.cs](these tests), however the tests do not specifically test StartsWith.

```csharp
using System;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;

namespace EffortBug
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var effortConnection = Effort.DbConnectionFactory.CreateTransient())
            {
                using (var db = new EntityDbContext(effortConnection))
                {
                    db.Database.CreateIfNotExists();
                    effortConnection.IsCaseSensitive = false;
                    db.Tests.Add(new Test { Name = "aa" });
                    db.SaveChanges();
                    // Simple case-insensitive equality works
                    var results1 = db.Tests.Where(p => p.Name == "AA").ToList();
                    Console.WriteLine($"results1 count = {results1.Count}");
                    // However case-insensitive StartsWith does not work (works with SQL server)
                    var results2 = db.Tests.Where(p => p.Name.StartsWith("A")).ToList();
                    Console.WriteLine($"results2 count = {results2.Count}");
                    // StartsWith will work as long as it can be case-sensitive.
                    var results3 = db.Tests.Where(p => p.Name.StartsWith("a")).ToList();
                    Console.WriteLine($"results3 count = {results3.Count}");
                    Console.ReadLine();
                }
            }
        }
    }
    public class EntityDbContext : DbContext
    {
        public EntityDbContext(DbConnection dbConnection) : base(dbConnection, false) { }
        public virtual DbSet<Test> Tests { get; set; }
    }
    public class Test
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
```

### Further technical details
- EF version: 6.2.0
- EF Effort version: 2.2.1
- Database Provider: Effort (broken) / SQL Azure (working)

**Comment by Agendum** [comment]
Looks like Contains and EndsWith also suffers from this. I discovered this bug while building unit tests against a larger project which uses both StartsWith and Contains.

**Comment by JonathanMagnan** [comment]
Hello @Agendum ,

Thank you for reporting. We will look at it if that's possible to support.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Agendum ,

Just to give you an update.

We checked the issue but it looks to be harder to support then we though. Since the DbFunctions is static, we currently don't found a good way to pass the value set in the connection.

Meanwhile a better on is found, as a workaround, we could add a global variable for `IsCaseSensitive`. On our side, using a global variable make it very easy to support and would require us only a few minutes to code (already tested your code).

Would you like to have this solution as a fix?

**Comment by Agendum** [comment]
The proposed solution sounds a lot like a 'DefaultIsCaseSensitive' for connections or something, which could be a way to make it forward compatible. For my situation that works just fine since I would set all connections to be case-insensitive. Thanks!

**Comment by JonathanMagnan** [comment]
Hello @Agendum ,

The v2.2.2 has been released.

We finally take a few more days to make it the right way.

It should now work without your additional code.

Let me know if you find another issue.
