### ISSUE TITLE
Support for views?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [zzzprojects/EntityFramework-Effort#181]
Hello. Does Effort provide support for views? Specifically, if I have a view that selects from tables A and B, then if I use Effort to insert rows into tables A and B, will those rows show up in the view?

I've given this a try, but it looks like I'm always getting `NULL` back when I do a `.FindAsync()` on the view, so I'm thinking that maybe there isn't yet support for this.

Thanks. Very useful project, by the way :)

**Comment by JonathanMagnan** [comment]
Hello @Bosch-Eli-Black ,

Unfortunately no, `Effort` doesn't support view. 

However, a view can be simulated probably by a method such as:

```csharp
public class MyContext : DbContext
{
	// ...code...
	
	public List<InvoiceHeaderItemView> GetInvoiceHeaderItem()
	{
		var invoices = this.Invoices.Include(x => x.Items).ToList();
		
		// ... create a projection to simulate the view	
		return invoices.Select(x => new InvoiceHeaderItemView() { InvoiceID = x.InvoiceID, ItemCount = x.Items.Count }).ToList();
	}
}

public class InvoiceHeaderItemView
{
	public int InvoiceID { get; set; }
	public int ItemCount { get; set; }
	
	// ...properties...
}
```

Let me know if that answer correctly to your question

**Comment by Bosch-Eli-Black** [comment]
Okay, that answers my question.

Thanks, @JonathanMagnan! :)
