### ISSUE TITLE
Updating entity by calling DbSet.Attach with detached entity throws InvalidOperationException

### ISSUE THREAD

**Issue by kubabuda** [zzzprojects/EntityFramework-Effort#192]
### Description
Trying to update entities that went through detaching (with AsNoTracking()) results in InvalidOperationException.

Sample code:
```
var detached = _context.AttachTests.AsNoTracking().First();
_context.AttachTests.Attach(detached);
```

Error:
```
Exception message:
Message: System.InvalidOperationException : Attaching an entity of type 'EffortAttachIssues.AttachTest' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.

Result StackTrace:	
at System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   at System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   at System.Data.Entity.DbSet`1.Attach(TEntity entity)
...
```
This prevents integration testing of my scenario.
I found no mention of  `DbSet<T>.Attach(T)` being not supported, hence I am submitting this issue.

### Project
Reproducing exception is done here:
https://github.com/kubabuda/EffortAttachIssues

### Further technical details
- EF version: 6.2.0, 6.3.0
- EF Effort version: Effort.EF6 2.2.6
- Database Provider: not needed to reproduce, not relevant IMO

**Comment by JonathanMagnan** [comment]
Hello @kubabuda ,

The problem is that you use the context globally. It's a variable outside of your test.

Which means that anything you add is being kept in the ChangeTracker.

It's similar to the following code: https://dotnetfiddle.net/wBg8El

You need to re-create the context for every unit test if you don't want to have some Change Tracker issues like this one. 

Let me know if everything is clear for you.

**Comment by kubabuda** [comment]
It worked. I have limited DbContext lifetime down to single test, and InvalidOperationException on Attach is no longer thrown. Thank you.

Now I observe yet another related behavior I was not expecting. Looking for reattached entity with Linq works only if I first explicitely enumerate DbSet by calling ToArray() on it. I would expect that behavior to be wrong, or am I missing something again?
Example below, I've also updated my EffortAttachIssues repo.
            
                var newName = "Updated";
                using (var context = new AttachTestDbContext(_connection))
                {
                    // Arrange
                    var detached = context.AttachTests.AsNoTracking().First();
                    detached.Name = newName;
                    // Act
                    context.AttachTests.Attach(detached);
                    context.SaveChanges();

                    // Assert: 
                    Assert.AreEqual(1, context.AttachTests.ToArray()
                        .Where(a => a.Name == newName).Count()); // Works. Linq on DbSet.ToArray() detects attached updated entity

                    Assert.AreEqual(1, context.AttachTests
                        .Where(a => a.Name == newName).Count()); // Exception.  Linq on DbSet fails to detect attached entity
            }
`

**Comment by JonathanMagnan** [comment]
Hello @kubabuda ,

That's how the `ChangeTracker` work.

The following line:
```csharp
// Act
context.AttachTests.Attach(detached);
context.SaveChanges();
```

It doesn't save in the database. When you attached your entity, you attached it in the `EntityState.Unmodified`.

You never saved it in the database.

---

The following code:

```csharp
// Assert: 
Assert.AreEqual(1, context.AttachTests.ToArray()
	.Where(a => a.Name == newName).Count()); // Works. Linq on DbSet.ToArray() detects attached updated entity
```

make a query to the "database" to materialize entity that doesn't exists locally. Since the entity existed locally, the `where` clause was correctly applied.

---

The following code:

```csharp
Assert.AreEqual(1, context.AttachTests
	.Where(a => a.Name == newName).Count()); // Exception.  Linq on DbSet fails to detect attached entity
```

made the `where` clause in the database. However, as specified initially, you never saved the value in the database.

Let me know if that explains it correctly why that's happening and there is no bug.

**Comment by kubabuda** [comment]
Hello,
I see. Adding line
`context.Entry(detached).State = EntityState.Modified;`
fixed my problem. You're right, and I've done goofed. Thanks for clarifying :)
