### ISSUE TITLE
Missing Effort.CsvTool

### ISSUE THREAD

**Issue by XutBest** [zzzprojects/EntityFramework-Effort#193]
### Description
In your documentation(https://entityframework-effort.net/export-data-to-csv), it link to Effort.CsvTool but there is 404 not found error.
https://github.com/zzzprojects/EntityFramework-Effort/tree/develop/Main/Source/Effort.CsvTool

### Exception
404 error

**Comment by JonathanMagnan** [comment]
You are right,

The branch do not longer exist.

However, you can find it in the master: https://github.com/zzzprojects/EntityFramework-Effort/tree/master/Main/Source/misc/Effort.CsvTool

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
