### ISSUE TITLE
Using multiple EDMX files within a single in-memory connection

### ISSUE THREAD

**Issue by cervengoc** [zzzprojects/EntityFramework-Effort#198]
Hello guys, sorry for posting my question here, but I did not get any attention on SO (see the SO post [here](https://stackoverflow.com/questions/60564922/using-multiple-edmx-files-within-a-single-in-memory-connection-with-entity-frame))

We have 3 separate EDMX models having different eneities. However, at the end of the day they're all mapped to the same physical database, and they might have some cross-references between each other.

We're trying to set up Entity Framework Effort to do in-memory testing, however it seems like it supports only a single entity connection metadata per connection.

```
var connection = Effort.EntityConnectionFactory.CreateTransient($@"name=OneOfMyEdmx");
```

Is it possible to somehow add more metadata reference to the same `EntityConnection`?

Thank you in advance for your help.

**Comment by JonathanMagnan** [comment]
Hello @cervengoc ,

That's a very good question.

I don't think this scenario is currently supported. But I will ask my developer to look at it and check if there is something we can do here.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @cervengoc ,

Unfortunately, after my developer investigated this, we will abandon this feature as he didn't find any solution yet.

There is currently no easy way to do it. Feel free to try it on your side and make a pull request if you find a solution.

Best Regards,

Jon

**Comment by cervengoc** [comment]
Thank you @JonathanMagnan for having a look into this, sorry for not replying on time. We'll see, if we have the resources to contribute I'll be happy to have a deeper look.

BR,
Zoltán

**Comment by JonathanMagnan** [comment]
awesome Zoltán, 

we will be looking forward to hearing from you. 

Jon
