### ISSUE TITLE
In memory db targeting specific migration

### ISSUE THREAD

**Issue by cybercop** [zzzprojects/EntityFramework-Effort#201]
I was wondering if it is also possible to run the in memory database that targets specific migration. I was able to create in memory database but it looks like the in memory database is based on current state of the domain entities.

**Comment by JonathanMagnan** [comment]
Hello @cybercop ,

Unfortunately no,

It's not possible and there is currently no plan to doing such features.

However, we will certainly look at it if a pull request is provided.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
