### ISSUE TITLE
Batch Update is not working with Effort.EF6

### ISSUE THREAD

**Issue by wiertara** [zzzprojects/EntityFramework-Effort#205]
### Description
I'm using Effort.ES6  and Z.EntityFramework.Plus.EF6 libraries but I'm unable to successfully run unit test that checks the status of BatchUpdate action. Unit test is calling a method that runs BatchUpdateExtensions.Update<T> but the DB context (using Effort) doesn't see the changes. I've installed package Z.EntityFramework.Plus.EF6.Effort but with no effects to the result. Should I somehow initialize Effort context to get BatchUpdate features?

My DB context initialization: var context = new CartDbContext(DbConnectionFactory.CreateTransient(), false);

Note: tested method is working fine using Entity Framework but the problem is only in unit test with Effort database.

### Further technical details
- EF version: 6.2.0
- EF Plus version: 1.12.22
- Effort.ES6: 2.2.10

**Comment by JonathanMagnan** [comment]
Hello @wiertara ,

Sorry for the long delay,

My developer tried it and everything work as expected. He never succeeds to reproduce the issue.

Do you think you could provide us a runnable project with the issue? It will help him to get started and fix the issue asap.
