### ISSUE TITLE
Exception querying context during unit test

### ISSUE THREAD

**Issue by Wheater** [zzzprojects/EntityFramework-Effort#207]
### Description
After saving changes in the context, querying them causes an exception with the following error. I cannot call FirstOrDefault, Where, ToList, etc. etc.

_context.Table.Find seems to work, but that is the only method of querying the context available.

### Exception
System.Data.Entity.Core.EntityCommandExecutionException : An error occurred while executing the command definition. See the inner exception for details.
    ---- System.ArgumentNullException : Value cannot be null.
    Parameter name: sql
  Stack Trace: 
    EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
    <>c__DisplayClass7.<GetResults>b__6()
    ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    <>c__DisplayClass7.<GetResults>b__5()
    DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
    ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
    IEnumerable<T>.GetEnumerator>b__0()
    LazyEnumerator`1.MoveNext()
    Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
    ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
    ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
    IQueryProvider.Execute[TResult](Expression expression)
    DbQueryProvider.Execute[TResult](Expression expression)
    Queryable.FirstOrDefault[TSource](IQueryable`1 source)
    SettingsMarketingToolsRepositoryTests.SomeTest() line 32
    ----- Inner Stack Trace -----
    QueryRegistrar.ContainsQuery(MetadataWorkspace workspace, String sql)
    CachingCommand.get_IsQueryAlwaysCached()
    CachingCommand.get_IsCacheable()
    CachingCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteReader(CommandBehavior behavior)
    DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
    InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
    DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
    InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteReader(CommandBehavior behavior)
    EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Example

```
        public SettingsMarketingToolsRepositoryTests()
        {
            var connection = Effort.DbConnectionFactory.CreateTransient();

            _context = new SettingsDbContext(connection);

            _context.Database.CreateIfNotExists();
        }

        [Fact]
        public void SomeTest()
        {
            _context.TblMarketingTools.Add(new TblMarketingTool { ToolId = 1, MsClient = _msClient, Name = "Tool1", Description = "Description 1" });
            _context.SaveChanges();
            var tool = _context.TblMarketingTools.FirstOrDefault();
        }
```

### Further technical details
- EF version: EF6
- EF Effort version: 2.2.10
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @Wheater ,
 
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Wheater** [comment]
@JonathanMagnan Honestly, I don't think it's feasible at this point and I have too many deadlines to meet. Maybe I can revisit this in the future.

**Comment by JonathanMagnan** [comment]
No problem,

Just let us know whenever you can provide an example and we will re-open the issue.

Best Regards,

Jon
