### ISSUE TITLE
Z.EntityFramework.Classic.Effort v 2.2.9 is not compatible with NMemory version 3.1.2

### ISSUE THREAD

**Issue by rmaenk** [zzzprojects/EntityFramework-Effort#209]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Z.EntityFramework.Classic.Effort v 2.2.9 (Latest available in nuget) is not compatible with NMemory version 3.1.2
Target framework version is 4.8.

## 2. Exception
```
Exception message:

Effort.Exceptions.EffortException: Unhandled exception while trying to initialize the content of 'Table<...>' table ---> System.MissingMethodException
...
 NMemory.Tables.Table`2.CalculateIdentityFeed()
```

## 3. Fiddle or Project
No available
package.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.4.0" targetFramework="net48" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.7" targetFramework="net48" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="3.1.1" targetFramework="net48" />
  <package id="Microsoft.SqlServer.Types" version="14.0.1016.290" targetFramework="net48" />
  <package id="MSTest.TestAdapter" version="2.1.2" targetFramework="net48" />
  <package id="MSTest.TestFramework" version="2.1.2" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net48" />
  <package id="NMemory" version="3.1.2" targetFramework="net48" />
  <package id="Z.EntityFramework.Classic" version="7.1.43" targetFramework="net48" />
  <package id="Z.EntityFramework.Classic.Effort" version="2.2.9" targetFramework="net48" />
  <package id="Z.EntityFramework.Extensions.Classic" version="5.1.31" targetFramework="net48" />
  <package id="Z.EntityFramework.Plus.QueryIncludeOptimized.EFClassic" version="1.8.16" targetFramework="net48" />
  <package id="Z.Expressions.Eval" version="4.0.41" targetFramework="net48" />
</packages>
```
Can be reproduced during adding an entity with identity column to DBSet in test.

## 4. Any further technical details
NMemory version 3.1.0 working without errors. The reason of the issue is changed signature of NMemory.Tables.Table`2.CalculateIdentityFeed method in (generic NMemory.Tables.Table class):
```
    protected void CalculateIdentityFeed(bool forceMinValue = false)
    {
      if (this.identityField == null)
        return;
      this.identityField.InitializeBasedOnData(this.primaryKeyIndex.SelectAll(), forceMinValue);
    }
```
"forceMinValue " parameter was introduced. Default value for parameter makes it looks like previous implementation, but in MSIL it is a method with parameter, but Effort expects a method without parameter.

**Note:** 
Z.EntityFramework.Classic.Effort v 2.2.9 package has requirements: 
.NETFramework, version=v4.5
   NMemory (>=3.0.0) - _this allows to use latest version of NMemory: 3.1.2_
   Z.EntityFramework.Classic (>= 7.1.24)

Thanks, 
Roman

**Comment by JonathanMagnan** [comment]
Hello @rmaenk ,

The v2.2.13 of `Z.EntityFramework.Classic.Effort` has been released.

Could you try it and let us know if everything is now working as expected?

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by rmaenk** [comment]
Hello @JonathanMagnan,
Version 2.2.13 is working fine.
Thanks,
Roman
