### ISSUE TITLE
Expose IdentitySpecification so we can change the seed value

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/EntityFramework-Effort#210]
Can you expose the IdentitySpecification  so we have a way to change the values? 
Thank you

**Comment by JonathanMagnan** [comment]
Sure,

I will ask my developer to check if that's already possible / to implement this

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

The v2.2.14 has been released.

It is now possible to set the identity seed and increment

Here is an example:

```csharp
var connection = Effort.DbConnectionFactory.CreateTransient();

using (var context = new EntityContext(connection))
{
	context.Database.CreateIfNotExists();
	connection.Open();

	connection.DbManager.SetIdentity<EntitySimple>(50);
	connection.DbManager.SetIdentity<EntitySimple2>(100, 2);
}
```

Let me know if you need some help to get started.

Best Regards,

Jon

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by tedypranolo** [comment]
Thank you so much. I had to do a lot of ugly workarounds using reflection. This will help a lot.
