### ISSUE TITLE
Move documentation drom codeplex to github Wiki

### ISSUE THREAD

**Issue by pokornyIt** [zzzprojects/EntityFramework-Effort#76]
Hello based on https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/ can you transfer project documentation from codeplex to this project wiki? 

"  In October, we’ll set CodePlex to read-only, before shutting it down completely on December 15th, 2017."

Thx

**Comment by JonathanMagnan** [comment]
Hello @pokornyIt ,

The documentation is now online here: http://entityframework-effort.net/

We will soon fully re-write it with some online example on https://dotnetfiddle.net/

Best Regards,

Jonathan
