### ISSUE TITLE
Stored Procedures in the In-Memory Database

### ISSUE THREAD

**Issue by Kingviech** [zzzprojects/EntityFramework-Effort#77]
Hello, thanks for your awesome library, it makes testing database connections very easy.

I've come across one question during the development of the test suite of the project I'm currently working on: Is there a way to mock Stored Procedures of the underlying database context?

If so is there any documentation available for this problem?

Thanks!

Update:
This is the exception which is thrown when trying to execute a stored procedure on the mocked effort db context:

System.NotSupportedException: Missing mapping for '<<StoredProcedureName>>' function
    bei Effort.Internal.DbCommandTreeTransformation.CanonicalFunctionMapper.CreateMethodCall(EdmFunction function, Expression[] arguments)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbFunctionExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbFunctionExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbJoinExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbJoinExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbJoinExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbProjectExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbFilterExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbProjectExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   bei Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context)
   bei Effort.Provider.EffortEntityCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   bei System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

**Comment by JonathanMagnan** [comment]
Hello @Kingviech ,

Sorry for the delay, it's not possible to mock your stored procedure.

The `NMemory` library allows creating stored procedure but I don't think that's exactly what you want to do.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
