### ISSUE TITLE
SqlQuery error: The provided parameter object is incompatible

### ISSUE THREAD

**Issue by paolorr** [zzzprojects/EntityFramework-Effort#81]
When I try to run the following code using Effort I receive this error, but if I run on a real SQL Server it works
`
var query = "SELECT * FROM ToolStatus where Id > @p0";
var @params = new List<SqlParameter>();
@params.Add(new SqlParameter("@p0", 1));var result = Context.Database.SqlQuery<ToolStatus>(query, @params.ToArray()).ToList();
`

Isn`t SqlQuery supported?

**Comment by JonathanMagnan** [comment]
Hello @paolorr ,

The answer is no.

`Effort` (or `NMemory` under the hood ) is not a real database. It works great with `LINQ` but it doesn't interpret and execute pure T-SQL.

So it will probably never work with SqlQuery. There is some memory database such as SQLite that perhaps will work better for your test: https://www.sqlite.org/inmemorydb.html

Best Regards,

Jonathan
