### ISSUE TITLE
Handling context with a constructor forwarding to base("name=Foo")

### ISSUE THREAD

**Issue by tlycken** [zzzprojects/EntityFramework-Effort#83]
Given a DbContext like `MyContext` below, and following e.g. [this blog post](https://blog.goyello.com/2016/07/14/save-time-mocking-use-your-real-entity-framework-dbcontext-in-unit-tests/) to implement in-memory testing with Effort.EF6, everything works as expected:

    public class MyContext : DbContext
    {
        public DbSet<MyEntity> MyEntities { get; set; }
    }

However, if I add a constructor like in the following example, it seems that Effort.EF6 doesn't manage to intercept the db provider:

    public class MyContext : DbContext
    {
        public MyContext() : base("name=FooDb") { }
        public DbSet<MyEntity> MyEntities { get; set; }
    }

So with this, instead of a successful test, I get an `InvalidOperationException`:

> System.InvalidOperationException : No connection string named 'FooDb' could be found in the application config file.
>   at System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()
>   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
>   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
>   at System.Data.Entity.Internal.Linq.InternalSet\`1.Initialize()
>   at System.Data.Entity.Internal.Linq.InternalSet\`1.get_InternalContext()
>   at System.Data.Entity.Internal.Linq.InternalSet\`1.AddRange(IEnumerable entities)
>   at System.Data.Entity.DbSet\`1.AddRange(IEnumerable\`1 entities)
>   at ClassLibrary1.Tests.ATest.<Sample>d__0.MoveNext() in c:\users\tomas\documents\visual studio 2017\Projects\NUnitEffort\ClassLibrary1.Tests\ATest.cs:line 14
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
>   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

Here's an [MWE reproducing the problem.](https://github.com/tamasflamich/effort/files/1372418/NUnitEffort.zip)

I realize this might not be Effort's fault - but how do I work around it, if changing the db context is not an option?

**Comment by RaringCoder** [comment]
Did you ever get anywhere with this? I've just hit the same problem.

**Comment by tlycken** [comment]
@RaringCoder I'll check our logs; we've since switched to EF Core and testing against an in-memory db instead, so I don't have the code infront of me...

(One of the main reasons for switching was that our data model became so complex that Effort wasn't fast enough...)

**Comment by tlycken** [comment]
@RaringCoder It seems what we eventually did, was to add a constructor to the `DbContext` which took a `DbConnection`. Then we could let Effort create that `DbConnection` instance and register it as a singleton in the DI container when spinning up the test server.

**Comment by RaringCoder** [comment]
Yeah I'm in the same boat. We have an existing model on EF6 and the new models on EF Core. Migration is a hopeful future activity but for now to get the team writing tests I wanted to get this running.

**Comment by RaringCoder** [comment]
Yeah I was bending that way myself. I didn't want to have to do it that way based on the same blog post you linked last year, but I've had no luck with it.

**Comment by RaringCoder** [comment]
Thanks for taking the time to reply 👍

**Comment by mattkoch614** [comment]
I'd like to add some additional detail to this, as we were experiencing the same issue and resolved it a slightly different way. We are leveraging a "model first" approach using an EDMX file. I should note that we were unable to get Effort working with the instructions this repo provides, as they seem specific to Code First implementations. Google search suggestions got us 1/2 of the way there but not 100%.

We are using Simple Injector in our web application which binds our base ``DbContext`` class to the DI container. Given this implementation, [we cannot create a second public constructor](http://simpleinjector.readthedocs.io/en/latest/decisions.html#one-constructor) on the ``DbContext `` partial class, so that method was out the window. What we ended up doing was creating a derived "fake" DbContext that extended from the base (where we set up a protected constructor) for our Unit Tests to leverage. That, coupled with ``Effort.EntityConnectionFactory.CreateTransient("name=MyEntities");`` got us to where we needed to be:

```csharp
    class FakeDbContext : MyEntities
    {

        /// <summary>
        /// This constructor is for test usage only!
        /// </summary>
        /// <param name="connection">Test connection for in memory database</param>
        public FakeDbContext(DbConnection connection) : base(connection)
        {

        }

    }

    public partial class MyEntities : DbContext, IDbContext
    {
        /// <summary>
        /// This constructor is for test usage only!
        /// </summary>
        /// <param name="connection">Test connection for in memory database</param>
        protected MyEntities(DbConnection connection) : base(connection, true)
        {

        }
    }

    //Unit test
    [TestClass]
    public class InMemoryTests
    {

        [TestMethod]
        public void foo_should_work_properly()
        {
            var connection = Effort.EntityConnectionFactory.CreateTransient("name=MyEntities");

            using (var model = new FakeDbContext(connection))
            {
                //TODO
            }
        }

    }

```

I hope this is helpful to someone, as we spent the better part of a day getting this to work.

**Comment by JonathanMagnan** [comment]
Hello all,

I will close this issue since it looks to be resolved with @mattkoch614 code.
