### ISSUE TITLE
Oracle Entity Framework Generated Context Exception:Schema specified is not valid. Errors: (0,0) : error 2019: Member Mapping specified is not valid. The type 'Edm.Boolean[Nullable=True,DefaultValue=]' ...

### ISSUE THREAD

**Issue by kachalkov** [zzzprojects/EntityFramework-Effort#9]
Hi, awesome Effort and code!
I'm trying to use it for Oracle, I've fixed Export CSV Tool, now I'm trying to run simple example:

var dl = new CsvDataLoader("...");
var connection = Effort.EntityConnectionFactory.CreateTransient("name=EapEntities", dl);
var db = new EapEntities(connection);
db.CM_HUMAN.Take(100).Dump();

and getting this errors:
MappingException: Schema specified is not valid. Errors: 
(0,0) : error 2019: Member Mapping specified is not valid. The type 'Edm.Boolean[Nullable=True,DefaultValue=]' of member 'DEFAULT_FLAG' in type 'Model.CE_CATALOG_ENTRY_NG' is not compatible with 'Effort.decimal[Nullable=True,DefaultValue=,Precision=1,Scale=0]' of member 'DEFAULT_FLAG' in type 'Model.Store.CE_CATALOG_ENTRY_NG'.
(0,0) : error 2019: Member Mapping specified is not valid. The type 'Edm.Boolean[Nullable=True,DefaultValue=]' of member 'CITY_LOOKUP_BROKEN' in type 'Model.CM_ADDRESS' is not compatible with 'Effort.decimal[Nullable=True,DefaultValue=,Precision=1,Scale=0]' of member 'CITY_LOOKUP_BROKEN' in type 'Model.Store.CM_ADDRESS'.
(0,0) : error 2019: Member Mapping specified is not valid. 

I've attached debugger and can see that error happening at:

   at Effort.Internal.Common.MetadataWorkspaceHelper.CreateMetadataWorkspace(List`1 csdl, List`1 ssdl, List`1 msl) 

at this line in  \effort-master\Main\Source\Effort\Internal\Common\MetadataWorkspaceHelper.cs

```
        StorageMappingItemCollection smic = new StorageMappingItemCollection(eic, sic, msl.Select(c => c.CreateReader()));
```

 at System.Data.Entity.Core.Mapping.StorageMappingItemCollection.Init(EdmItemCollection edmCollection, StoreItemCollection storeCollection, IEnumerable`1 xmlReaders, IList`1 filePaths, Boolean throwOnError)
   at System.Data.Entity.Core.Mapping.StorageMappingItemCollection..ctor(EdmItemCollection edmCollection, StoreItemCollection storeCollection, IEnumerable`1 xmlReaders)
   at Effort.Internal.Common.MetadataWorkspaceHelper.CreateMetadataWorkspace(List`1 csdl, List`1 ssdl, List`1 msl)
   at Effort.Internal.Common.MetadataWorkspaceHelper.Rewrite(String metadata, String providerInvariantName, String providerManifestToken)
   at Effort.EntityConnectionFactory.<GetEffortCompatibleMetadataWorkspace>b__1(String metadata)
   at Effort.Internal.Caching.MetadataWorkspaceStore.<>c__DisplayClass1.<GetMetadataWorkspace>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Effort.Internal.Caching.ConcurrentCache`2.Get(TKey key, Func`1 factory)
   at Effort.Internal.Caching.MetadataWorkspaceStore.GetMetadataWorkspace(String metadata, Func`2 workspaceFactoryMethod)
   at Effort.EntityConnectionFactory.GetEffortCompatibleMetadataWorkspace(String& entityConnectionString)
   at Effort.EntityConnectionFactory.CreateTransient(String entityConnectionString, IDataLoader dataLoader)
   at UserQuery
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Any ideas appreciated :+1:

**Comment by tamasflamich** [comment]
Hi,

I have never messed with Oracle compatible EDMX files. Could you share me the parts mentioned by the error message?

**Comment by andersthorsen** [comment]
Hi,
I have the same problem.

This is how the column is defined in the EDMX:

<Property Name="PROCESS_RESTARTED" Type="number" Precision="1" Scale="0" />

<Property Name="PROCESS_RESTARTED" Type="Boolean" />

<ScalarProperty Name="PROCESS_RESTARTED" ColumnName="PROCESS_RESTARTED" />

**Comment by emilievix** [comment]
Hi,

Same issue for me with all fields with Oracle Number(1) type that are mapped as boolean in my model. 
Is there any update on the subject or any workaround ?

thx

**Comment by JonathanMagnan** [comment]
Hello @emilievix ,

Could you provide us a project with this issue including the SQL to create the tables?

It will help my developer to get started faster.

Best Regards,

Jonathan

**Comment by emilievix** [comment]
Hi @JonathanMagnan ,

Unfortunately, I can't give you the project since it is a (huge) commercial application (and of course, as usual, I'm running out of time on the subject to create a sample project).

I have this issue for all fields that are set to boolean type in my edmx model. 
These fields are all mapped to fields defined as number(1) in my Oracle database (I think this is a new default mapping for EF6 / ODP.NET). 
When I modify the type of the field in the edmx model (to Int16 for example), the mapping issue with Effort disappears.

I suppose that just creating a table with such a field, and create a model that includes this table should allow to reproduce the issue.

Sorry that I can't provide more to help you start in better conditions...

Best regards,
Emilie.

**Comment by lssilveira11** [comment]
> Hi,
> 
> Same issue for me with all fields with Number(1) Oracle type that are mapped as boolean in my model.
> Is there any update on the subject or any workaround ?
> 
> thx

Hi, 

I have this exact same problem here right now.
Is there any workaround available at this time?

**Comment by lssilveira11** [comment]
What is happening is that the Oracle Provider accept an "mapping configuration", so every field of type number(1,0) will be mapped to boolean (it will store 1 for true and 0 for false), simulating the bit type on SQL Server.

How can I configure this mapping on Effort provider, so it can map number(1,0) members to Edm.Boolean, instead of decimal(1,0)?

**Comment by JonathanMagnan** [comment]
Hello @lssilveira11 ,

It might be possible but it will require a global option and all number with precision one will now be decimal(1,0) instead when this option is set to `true`. It's something that could work for you?

**Comment by JonathanMagnan** [comment]
Oh, I misread your comment. We will look at it this week ;)

Perhaps no option will be required.

**Comment by JonathanMagnan** [comment]
Hello @lssilveira11 ,

My developer asked me if you could provide him with a unit test project with this error including the `script` required to create the table.

_You can send it to: info@zzzprojects.com if you need to keep the source private_

He has made some research, unfortunately, it doesn't look as simple as I thought to fix it.

We will need to check how `Oracle` handle this config to change the mapping from `ProviderManifest.xml`

**Comment by lssilveira11** [comment]
Hi @JonathanMagnan ,

I made an Example Mapping App that reproduces this problem exactly. Please, clone this repository and follow the instructions to run the app. When you run the tests, you will see this problem happening.

ExampleMappingApp: https://github.com/lssilveira11/examplemappingapp.git

**Comment by lssilveira11** [comment]
Hi! Any news about this problem?

**Comment by JonathanMagnan** [comment]
Hello @lssilveira11 ,

Unfortunately when we tried, we didn't successfully find how to fix it ;(

I thought it would have been easy at first but after spending some time on it, we didn't reach any solution to make it work correctly

So I guess, for now, it will be unsupported.

**Comment by JonathanMagnan** [comment]
Hello everyone,

We still have not fully solved this issue but it is now possible to provide a Manifest to Effort which should do the job.

So it is possible on your side to customize the manifest the way you want. However, it doesn't mean that other type not specified in the original manifest will work since it might require some custom logic.

I have attached an example.

Let me know if you have question

[Console.zip](https://github.com/zzzprojects/EntityFramework-Effort/files/3374169/Console.zip)
