### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by josh-endries** [zzzprojects/EntityFramework-Effort#90]
I'm not sure if I am using it properly so this is what I did...

- Installed into my test project via NuGet.
- Added Effort.Provider.EffortProviderConfiguration.RegisterProvider() to my AssemblyInitialize method.
- Created a constructor in my DbContext like so: public MyContext(DbConnection dbc) : base(dbc, true) {}
- Instantiate my context like so:
            using (var dbc = Effort.DbConnectionFactory.CreateTransient())
            using (var db = new InventoryContext(dbc))
- Try to insert a new entity like so:
            var foo = db.Foos.Add(new Foo
                {
                    Name = $"Unit Test {guid.ToString()}"
                });

On that line is where the exception occurs. From looking around at other issues, it sounds like maybe we use a column type that Effort doesn't support?

I'm using code first.

**Comment by SuperJMN** [comment]
Same happens to me

**Comment by JonathanMagnan** [comment]
Hello @josh-endries , @SuperJMN ,

Do anyone of you could provide us a project with this issue?

We already tried it and everything works perfectly on our side. So yes, perhaps we are missing something such as column type that's not supported.

Best Regards,

Jonathan

**Comment by LazarSebi** [comment]
I get the same error, in my case i have a varchar column in the database and a string field on the model. I have to explicit the type, in order for EF to use this column properly.
So i tried two methods:
1.   In the Person model class:
        [Column(TypeName = "nvarchar")]
        public string EmailAddress { get; set; }
2.   In the PersonConfiguration class:
Property(x => x.EmailAddress).HasColumnName("EmailAddress").IsOptional().HasMaxLength(256).HasColumnType("varchar");

For both cases the code works correctly, and the type used for queering the database is varchar. Unfortunately all the unit tests fail with System.InvalidOperationException: Sequence contains no matching element.

**Comment by JonathanMagnan** [comment]
Hello @LazarSebi ,

We made a lot of change in the past months. The support for `nvarchar` is now available.

Do you think you could try it again and let us know if everything works as expected?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been probably resolved a few months ago.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
