### ISSUE TITLE
Cannot load CSV data from a <Link> file.

### ISSUE THREAD

**Issue by CarnivalBen** [zzzprojects/EntityFramework-Effort#96]
I'm using Effort to mock my database and provide test data in the form of CSV files for my unit tests.

I have a big solution with a few separate test projects, but they all need the same test data, so I have created a folder at the root of the solution and put a load of CSVs there, each containing test data for all of the db tables.

If I run my tests locally and reference the CSVs by relative path, then everything is good, but when I get my TeamCity setup to run the tests they fail because of pathing issues.

So, to solve this, I created a link to the CSVs in my .csproj file, and marked them as embedded resources, and referenced them as resources from the Effort data loader.

Problem is, Effort can't find or see the resource files when they're linked.

It all looks something like this:

```
    Solution
    +  Project1
    -  Project1.Tests
    |  -  MyUnitTests.cs
    |  -  TestData
    |     -  Table1.csv <- linked file
    |     -  Table2.csv <- linked file   
    +  Project2
    -  Project2.Tests
    |  -  MyUnitTests.cs
    |  -  TestData
    |     -  Table1.csv <- linked file
    |     -  Table2.csv <- linked file
    +  TestData
       -  Table1.csv
       -  Table2.csv
```

I've linked the test data files by adding this to the .csproj file manually via a text editor:

```
    <ItemGroup>
      <EmbeddedResource Include="..\..\TestData\*.csv">
        <Link>TestData\%(FileName)</Link>        
      </EmbeddedResource>
    </ItemGroup>
```

I reference the files from Effort like this:

`    _dataLoader = new CsvDataLoader("res://Project1.Tests/TestData/");`

When I try to run my tests, I just end up with empty mocked tables with no test data in them, and so my tests fail.

I know that Effort can see the TestData folder, because if I change the reference path to some dummy path (`res://Project1.Tests/Dummy/`) then I get an error.

I have also used [ILSpy][1] to inspect the DLL after building the project, and it all looks good, I can see the embedded resource files and their contents.

Also, if I delete the linked files and replace with actual files, then it works fine. This isn't a good solution though because I then have to maintain two copies of the same test data.

Anybody know why it doesn't work when using `<link>` files?

  [1]: https://github.com/icsharpcode/ILSpy#ilspy-------

**Comment by JonathanMagnan** [comment]
Hello @CarnivalBen ,

Do you think you could share a complete test project with the current issue?

It will help my developer to get started faster when he will investigate it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @CarnivalBen ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
