### ISSUE TITLE
Can I switch off the identity columns while loading tabels

### ISSUE THREAD

**Issue by rwahib** [zzzprojects/EntityFramework-Effort#97]
I have a problem, that I want to Initialise the the Entity with data was generated from db and exported in files, but when I loaded it generates error, because it resets all keys to 1,2,3

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

it looks there is some way to do it by looking at the unit test.

Please see: https://github.com/zzzprojects/EntityFramework-Effort/blob/4c580eb9b72cdc5d08345c0b096b3fbfb48c63d9/Main/Source/Effort.Test.EF6/DbManagerFixture.cs

```csharp
connection.DbManager.SetIdentityFields(false);
```

I believe you will find your answer here ;)

Best Regards,

Jonathan

**Comment by rwahib** [comment]
Hi 
this is the code that I am using
I use database first
 var connection = EntityConnectionFactory.CreateTransient("name=SampleProjectTemplateEntities");

when I tried to use the code above it generated many errors like this

_protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            **throw new UnintentionalCodeFirstException();**
        }_

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

Could you provide us a test project or a full example?

We will try to provide some help by using what you have done

For example:

```csharp
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Effort.DataLoaders;

namespace Request
{
    public static class Request_Effort
    {
        // remove comment her and in public EntityContext() : base(connection) for true connection, so without Effort
        // public const string connection = "Server=127.0.0.1;Initial Catalog=Z;Integrated Security=True;"; // for true connection
        public static void Execute()
        {
            DbConnection connection = Effort.DbConnectionFactory.CreateTransient();

            // CLEAN
            using (var context = new EntityContext(connection))
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext(connection))
            {
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 1 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 2 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 3 });
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext(connection))
            {
                var list = context.EntitySimples.ToList();
            }


        }

        public class EntityContext : DbContext
        {
            // for true connection
            //public EntityContext() : base(connection)
            //{ 
            //}

            public EntityContext(DbConnection connectionString)
                : base(connectionString, true)
            { 
            }

            public DbSet<EntitySimple> EntitySimples { get; set; } 

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; } 
        } 
    }
}
```

Best Regards,

Jonathan

**Comment by rwahib** [comment]
Hi I am not using code first
I am using database first, and I have a factories based on Microsoft Unity that Load data from c# files dynamically ( generated from db as samples controlled by options via console application, take up to 30 seconds to be generated )

samples of these files in the attached zip 

# web.config snippet 

`<connectionStrings>
    <add name="SampleProjectTemplateEntities" connectionString="metadata=res://*/SampleProjectTemplate.csdl|res://*/SampleProjectTemplate.ssdl|res://*/SampleProjectTemplate.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=*****;initial catalog=*******-Template;persist security info=True;user id=sa;password=*****;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
`

# SampleProjectTemplateEntities snippet 

```
 public partial class SampleProjectTemplateEntities : DbContext
    {
        public SampleProjectTemplateEntities()
            : base("name=SampleProjectTemplateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppEntityType> AppEntityTypes { get; set; }
        public virtual DbSet<AppObjectInfo> AppObjectInfoes { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<CapabilityBehaviourIndicator> CapabilityBehaviourIndicators { get; set; }
        public virtual DbSet<CapabilityGroup> CapabilityGroups { get; set; }
        public virtual DbSet<CapabilityLevel> CapabilityLevels { get; set; }
        public virtual DbSet<CapabilityName> CapabilityNames { get; set; }
        public virtual DbSet<CostCentreDetail> CostCentreDetails { get; set; }
        public virtual DbSet<Directorate> Directorates { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }


```
```
 public partial class SampleProjectTemplateEntities : DbContext
    {
        public SampleProjectTemplateEntities(DbConnection connection)
            : base(connection,true) {
        }
    }

```

# UnitOfWorkEntityMockup snippet 

 ```
class UnitOfWorkEntityMockup : UnitOfWork
    {
        public UnitOfWorkEntityMockup()
        {
           
            var connection = EntityConnectionFactory.CreateTransient("name=SampleProjectTemplateEntities");
            this.Db = new SampleProjectTemplateEntities(connection);

        }

    }

```

# MockRepositoryFactory:RepositoryFactory snippet


```
public class MockRepositoryFactory:RepositoryFactory
    {
        private readonly DatabaseMockMode _dbMockMode;

        public MockRepositoryFactory(DatabaseMockMode dbMockMode=DatabaseMockMode.LocalDb)
        {
            _dbMockMode = dbMockMode;
        }
       
        protected const string UnitTestToken = "@UNIT_TEST";
        public override void RegisterAllDependencies()
        {
            RegisterBaseDependencies();

            switch (_dbMockMode)
                {
                    case DatabaseMockMode.None:
                    // Container.RegisterInstance<IUnitOfWork>(unitOfWork); already registered
                    break;
                    case DatabaseMockMode.LocalDb:
                        Container.RegisterInstance<IUnitOfWork>(new UnitOfWorkLocalDbMockup()); 
                    break;
                    case DatabaseMockMode.EntityFrameworkMock:
                        Container.RegisterInstance<IUnitOfWork>(new UnitOfWorkEntityMockup());
                    break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            ;

            
            
        }
```



# EntityLoadManager snippet

  ```
public void Load(EntityType entityType, bool dependency = true) {

            if (this._loadedStatus.ContainsKey(entityType.Name) && this._loadedStatus[entityType.Name]) return;
            var loader = GetLoader(entityType);
            this._loadedStatus[entityType.Name] = true;

            var listofValues = loader?.Load();

            if (listofValues == null) return;

// loading entity dynamically             **_DbContext.Set(Type.GetType(T4Helper.GetFullClassName(entityType))).AddRange(listofValues);_**

            if (dependency) {
                var lookupEntities = T4Helper.GetLookupEntities(entityType);
                foreach (var lookupEntity in lookupEntities) {
                    Load(lookupEntity);
                }
            }

        }

```
[samples.zip](https://github.com/zzzprojects/EntityFramework-Effort/files/1768572/samples.zip)

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

Do you think you could provide me a working project?

You provided me some file, but there is still some file missing such as the `EDMX`. If you can provide a working project, I will be happy to look at it.

Unfortunately, with all demands/projects we support, we cannot longer try to create projects on our side due to time issue. We only debug working project.

Best Regards,

Jonathan

**Comment by rwahib** [comment]
Dear Jonathan
this is the project file
https://www.dropbox.com/s/5s6r6gs088yno8p/Sample.zip?dl=0


![image](https://user-images.githubusercontent.com/3424567/37000230-dbd57224-2116-11e8-982c-ffa5c930a00a.png)

Please run the unit test for SysMessageRepository and SysMesgCategory

you will see how the loader class will try to load data automatically either for one entity or all entity ( you have manually to choose in the initializer) 

these are the tables that have identity columns if you can switch them off after 
the **loader.loadAll()**  and before the **loader.SaveChanges()** will be great
this is the step that I am stuck

any help will be appreciated

TABLE_NAME	COLUMN_NAME
CapabilityGroup	CapabilityGroupId
CapabilityLevel	CapabilityLevelId
CapabilityName	CapabilityNameId
Focus	FocusId
GeneralLog	LogId
KeyRelationship	KeyRelationshipId
LookupFocusGradeCriteria	LookupId
Position	PositionId
PositionHistory	PositionHistoryId
PositionNote	PositionNoteId
RolePositionDescriptionHistory	RolePositionDescriptionHistoryId
sysdiagrams	diagram_id
if I have any table like GeneralLog that has identity I must add ids in sequence,

**Comment by JonathanMagnan** [comment]
Thank you @rwahib ,

My developer will try to look at this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

It's possible that we need the database to reproduce this issue?

You can send it here if you want to keep it private: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by rwahib** [comment]
Dear Jonathan 
I am working in Gov sector and this projrect is one of the most senstive projects, as it is the template that genetate the code of other projects 

Thar is why 
I spent time to replace all web services and db info and make this working version

However
I believe that we do not need a database at all, 


The full dmx with all classes is there
The effort library it should work and mock any dependancy on db

And it works with me very well

I can integrate the Effort with all microsoft unity dependency injections and service locator factories

And all the test initialisations are happend automatically via the loader services using reflections and metadata

The only problem is when I have an Identity key in an entity when I insert multiple values and I need a certain keys to maintain the relationships 

Thank you

**Comment by JonathanMagnan** [comment]
No problem,

I will forward this answer to my developer. I'm currently only the messenger ;)

Best regards,

Jonathan

**Comment by rwahib** [comment]
(Y)

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

My developer has run all unit tests and it seems to work.

However, we have not found anywhere where you added the line `connection.DbManager.SetIdentityFields(false);` to fix the loaded error you had in the first topic.

Best Regards,

Jonathan

**Comment by rwahib** [comment]
This is Great
Now please always use loader.LoadAll()
Version

I did not use SetIdentityFields(false) in this project I just want to make it work perfect in your end

Please set this line of code anywhere you like

Otherwise I will give you another version that this line of code there and not working

**Comment by rwahib** [comment]
So tell me if you want me to send the broken version

Regards

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

Sure, send us the broken version ;) It is always easier on our side this way.

Best Regards,

Jonathan

**Comment by rwahib** [comment]
Hi
this link is using the switch off identity, and will generate and error as this code is not code first
thank you

`https://www.dropbox.com/s/7nfpqb0fwmm4bkg/SampleWithBug.zip?dl=0`

**Comment by JonathanMagnan** [comment]
Hello @rwahib ,

We investigated this issue last week but unfortunately, we didn't success to fix it. I do not think at this moment we can support your scenario.

**Comment by rwahib** [comment]
Ok
Thank you for your efforts 
I will close this issue
