### ISSUE TITLE
DataLoader for CodeFirst Context loading

### ISSUE THREAD

**Issue by libenY** [zzzprojects/EntityFramework-Effort#99]
This might already be possible but I couldn't find a way to getting it to work.

```
var dataLoader = new EntityDataLoader("name=SqlClientConnection");
DbConnection dbConnection = DbConnectionFactory.CreateTransient(dataLoader);
var myContext = new MyContext(_dbConnection);
```

Configuration for database connection:
`<add name="SqlClientConnection" connectionString="Data Source=.\sqlexpress;Initial Catalog=MyDatabase;Integrated Security=True;MultipleActiveResultSets=true;" providerName="System.Data.SqlClient" />`

When loading this is throwing errors.
"The specified named connection is either not found in the configuration, not intended to be used with the EntityClient provider, or not valid."

If the connection string is based on the System.Data.SqlClient provider this will not work as it is expecting EntityClient provider connection, but the EntityClient provider connection is used more for the database first connections and is not applicable for Code First. When trying to create a connection using the EntityClient provider but without the model files, again there are errors on loading as it expects the metadata property to have a value.

So this is a first question is it possible to get the loader working for CodeFirst? And if so how?

If not then I guess this should be documented its not possible and maybe a new feature request.

**Comment by JonathanMagnan** [comment]
Hello @libenY ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

Best Regards,

Jonathan

**Comment by libenY** [comment]
Hi Jonathan,

Thanks for looking into it.

I've attached the test project.
[LoadRecordsFromSqlClientConnection.zip](https://github.com/zzzprojects/EntityFramework-Effort/files/1780527/LoadRecordsFromSqlClientConnection.zip)

Hopefully my intent is clear, let me know if you have any questions.

Regards

Liben

**Comment by JonathanMagnan** [comment]
Hello @libenY ,

The DataLoader support for code first has been added in v1.3.3

You will need however to specify a context factory (that's used under the hood to make this feature work).

For example

```csharp
EntityFrmeworkEffortManager.ContextFactory = (currentContext) => new EntitiesContext()
```

Best Regards,

Jonathan

**Comment by libenY** [comment]
Hi Jonathan,

I've just tested and its working, thanks a lot.

For anyone else trying to load using Code First the below snippet should help:

`
EntityFrameworkEffortManager.ContextFactory = context => new MyContext();

var dataLoader = new EntityDataLoader();
DbConnection dbConnection = DbConnectionFactory.CreateTransient(dataLoader);
var effortContext = new MyContext(dbConnection);
`

Regards

Liben

**Comment by dis081278** [comment]
Where do you pass the connection string?
